insert into Products (Name, Price, QuantityInStock) values ('Lid - Translucent, 3.5 And 6 Oz', '0.17', 89);
insert into Products (Name, Price, QuantityInStock) values ('Smoked Paprika', '4.90', 46);
insert into Products (Name, Price, QuantityInStock) values ('Crawfish', '3.81', 26);
insert into Products (Name, Price, QuantityInStock) values ('Wine - White, Gewurtzraminer', '7.41', 96);
insert into Products (Name, Price, QuantityInStock) values ('Wine - White, Ej', '5.07', 40);
insert into Products (Name, Price, QuantityInStock) values ('Gelatine Leaves - Bulk', '9.30', 15);
insert into Products (Name, Price, QuantityInStock) values ('Toamtoes 6x7 Select', '4.54', 2);
insert into Products (Name, Price, QuantityInStock) values ('Nantucket Orange Juice', '8.84', 15);
insert into Products (Name, Price, QuantityInStock) values ('Dawn Professionl Pot And Pan', '4.72', 48);
insert into Products (Name, Price, QuantityInStock) values ('Pepper - Orange', '1.96', 96);
insert into Products (Name, Price, QuantityInStock) values ('Tea Leaves - Oolong', '2.30', 53);
insert into Products (Name, Price, QuantityInStock) values ('Soup - Canadian Pea, Dry Mix', '9.69', 47);
insert into Products (Name, Price, QuantityInStock) values ('Table Cloth - 53x69 Colour', '1.32', 92);
insert into Products (Name, Price, QuantityInStock) values ('Coffee - Decafenated', '0.92', 84);
insert into Products (Name, Price, QuantityInStock) values ('Cheese - Cheddarsliced', '0.15', 56);
insert into Products (Name, Price, QuantityInStock) values ('Oyster - In Shell', '6.52', 30);
insert into Products (Name, Price, QuantityInStock) values ('Cardamon Seed / Pod', '9.44', 55);
insert into Products (Name, Price, QuantityInStock) values ('Lobster - Canned Premium', '9.48', 43);
insert into Products (Name, Price, QuantityInStock) values ('Nantucket - Pomegranate Pear', '3.37', 51);
insert into Products (Name, Price, QuantityInStock) values ('Wine - Rhine Riesling Wolf Blass', '2.29', 39);
insert into Products (Name, Price, QuantityInStock) values ('Salt - Celery', '8.57', 23);
insert into Products (Name, Price, QuantityInStock) values ('Lid - Translucent, 3.5 And 6 Oz', '1.46', 82);
insert into Products (Name, Price, QuantityInStock) values ('Apricots - Dried', '8.90', 3);
insert into Products (Name, Price, QuantityInStock) values ('Wine - Niagara,vqa Reisling', '4.96', 28);
insert into Products (Name, Price, QuantityInStock) values ('Gloves - Goldtouch Disposable', '6.84', 99);
insert into Products (Name, Price, QuantityInStock) values ('Juice - Prune', '7.91', 20);
insert into Products (Name, Price, QuantityInStock) values ('Sole - Iqf', '5.33', 28);
insert into Products (Name, Price, QuantityInStock) values ('Wine - Coteaux Du Tricastin Ac', '7.43', 59);
insert into Products (Name, Price, QuantityInStock) values ('Potatoes - Mini White 3 Oz', '1.21', 89);
insert into Products (Name, Price, QuantityInStock) values ('Wine - Riesling Dr. Pauly', '4.37', 98);
insert into Products (Name, Price, QuantityInStock) values ('Glass - Wine, Plastic, Clear 5 Oz', '5.23', 52);
insert into Products (Name, Price, QuantityInStock) values ('Vodka - Smirnoff', '6.77', 100);
insert into Products (Name, Price, QuantityInStock) values ('Lettuce - Green Leaf', '1.28', 92);
insert into Products (Name, Price, QuantityInStock) values ('Pork - Liver', '6.95', 32);
insert into Products (Name, Price, QuantityInStock) values ('Potatoes - Mini Red', '9.55', 38);
insert into Products (Name, Price, QuantityInStock) values ('Beer - Original Organic Lager', '3.66', 98);
insert into Products (Name, Price, QuantityInStock) values ('Clam - Cherrystone', '4.62', 24);
insert into Products (Name, Price, QuantityInStock) values ('Dc - Frozen Momji', '1.31', 80);
insert into Products (Name, Price, QuantityInStock) values ('Soup Campbells Turkey Veg.', '5.72', 33);
insert into Products (Name, Price, QuantityInStock) values ('Baking Soda', '4.33', 59);